<div class="navbar">
<nav>
    <div class="nav-wrapper #66bb6a green lighten-1">
            <a href="#!" class="brand-logo">My Portfolio</a>
    <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>


      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="index.php">Home</a></li>
          <li><a href="portfolio.php">Portfolio</a></li>
          <li><a href="contactform.php">Contact Form</a></li>
      </ul>

      <ul class="side-nav" id="mobile-demo">
          <li><a href="index.php">Home</a></li>
          <li><a href="portfolio.php">Portfolio</a></li>
          <li><a href="contactform.php">Contact Form</a></li>
      </ul>

    </div>
  </nav>
</div>

      
